apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-docker
  namespace: argocd

spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: manifest
    repoURL: 'https://github.com/vladoz77/gitops-docker-test'
    targetRevision: main
  sources: []
  project: apps2deploy
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
